import RPi.GPIO as GPIO
import time

LED_PIN1 = 5
LED_PIN2 = 6
LED_PIN3 = 7
SWITCH_PIN1 = 11
SWITCH_PIN2 = 10
SWITCH_PIN3 = 9

GPIO.setmode(GPIO.BCM)
GPIO.setup(LED_PIN1, GPIO.IN)
GPIO.setup(LED_PIN2, GPIO.IN)
GPIO.setup(LED_PIN3, GPIO.IN)
GPIO.setup(SWITCH_PIN1, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
GPIO.setup(SWITCH_PIN2, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
GPIO.setup(SWITCH_PIN3, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)